### ISSUE TITLE
Thanks for the wonderful tool

### ISSUE THREAD

**Issue by Sribalajivelan** [yzhengfei/ai-coding#124]
It's great tool and most of the JetBrains AI assistant feature covered, but the Doc generation missing, if possible add please, if you need any help from developer view, feel free to contact me

**Comment by yzhengfei** [comment]
Thank you for your feedback. The document generation function is a good suggestion, but it needs some time for research and development. Thank you.

**Comment by yzhengfei** [comment]
Hi, the document generation feature is now available. Please upgrade AI Coding to version 2024.1.16 or higher. The latest version, 2024.1.17, has optimized the display. The plugin is still under review. Thank you for your support.
