### ISSUE TITLE
Why Ai coding has only 5 chat while the same account on copilot website has 30! with  the seame session!

### ISSUE THREAD

**Issue by beshoo** [yzhengfei/ai-coding#129]
![image](https://github.com/user-attachments/assets/51b735d2-e36b-4a7e-be47-bb3937ba6924)

Regards

**Comment by yzhengfei** [comment]
Hi, New Bing has released a new version. After comprehensive consideration, I've decided to temporarily pause maintenance on New Bing and focus on developing new features for the plugin. I recommend using Google Gemini, which is also free. Although it cannot access the internet, it is sufficient for everyday development use. Thank you for your support.

**Comment by beshoo** [comment]
Gemini is stupid compared to GPT. In php laravel , it like to talk a lot with ni valuable solutions.

What am saying why the plugin give only 5 chats while the same cookies in the browser give you 30?

**Comment by beshoo** [comment]
@yzhengfei please may you tell us why you limit the chat to 5?
Regards

**Comment by yzhengfei** [comment]
I apologize for the delayed reply, I've been quite busy lately.
Here's the specific situation:
1. The 5 chat limit is returned by the New Bing interface, the plugin itself doesn't impose any limit.
2. New Bing has undergone upgrades and revisions (with significant changes to the HTTP request interface), and I'm no longer able to debug why it's limited to 5 chats.
3. After careful consideration, New Bing will no longer be maintained, unless New Bing releases an open API.

Thank you for your support.

I see it has now changed to what's shown below:

![image](https://github.com/user-attachments/assets/bee833d9-1fef-4126-a60a-44c173a1d5ad)
![image](https://github.com/user-attachments/assets/6c79377c-4af2-4ea8-bbef-a85c4b9835d6)
