### ISSUE TITLE
自定义模型中可以添加FIM功能吗？

### ISSUE THREAD

**Issue by lucacicii** [yzhengfei/ai-coding#158]
![image](https://github.com/user-attachments/assets/2da8bafb-8bc3-498a-879e-b39b009e17e5)
在这里能获取到上下文信息吗？添加额外的参数实现FIM

**Comment by yzhengfei** [comment]
选择**Code Completions**这个Tab，这里专门提供代码提示设置的地方，FIM取决于模型，这里提供了几个模版
**Generic** ：适用于不支持FIM的模型，可以根据模型，自定义提示词
**Code llama**/**CodeGemma**/**Code Qwen** : 支持FIM

![image](https://github.com/user-attachments/assets/b9485b69-ffda-4dc4-9f19-04df14d66168)

点击Test按钮可以测试调试模型
![image](https://github.com/user-attachments/assets/5fca1f89-e082-4fb4-84a7-8b98362c190b)

Prompt template窗口里的 **$ATTACHMENTS** 就是光标附近代码上下文，具体上下文效果参考上图promt窗口

**Comment by lucacicii** [comment]
这个prompt模板 和 code block starting regex 实在搞不定了。
这个siliconflow.cn是一个api聚合网站， 提供的两个coder类型的 一个deepseek，一个qwen-coder，两个都是支持FIM。
问题1：不知道怎么调整code block starting regex，实现FIM
问题2：qwen-coder在generic模式下 test是有结果的，但是在编辑器里面就不显示结果。
麻烦解答一下。
如果需要我提供实验的 api key 可以给我发信息。
![1](https://github.com/user-attachments/assets/3a738bb6-5f48-4680-8b11-1b69706ac78d)
![2](https://github.com/user-attachments/assets/f578953f-b355-4f58-ae4b-ae9ec8dec230)

**Comment by lucacicii** [comment]
大概知道了，可能大模型 是对 FIM 模板的 解析不太好，有时成功，有时失败，generic 模板反而是相对来讲，表现最稳定的

**Comment by yzhengfei** [comment]
这种FIM接口方式原来不支持，我做了一下改造，先安装这个版本（此版本还没上架IDEA市场）
[AI Coding-2024.1.19.zip](https://github.com/user-attachments/files/17532999/AI.Coding-2024.1.19.zip)

安装后，新建自定义AI：
![image](https://github.com/user-attachments/assets/5dbe3157-1ddb-4b4a-9fca-46c706dcd75a)

选择Open AI FIM模版
![image](https://github.com/user-attachments/assets/120e90b3-afc3-4525-b1db-ae6de1d1ec52)

更改链接/密钥和模型名
![image](https://github.com/user-attachments/assets/d123fa78-1236-4037-afca-1162ef34e6d6)

保存后Code completion选择刚刚设置的AI
![image](https://github.com/user-attachments/assets/696829e0-3cb8-48d3-857e-c635d21e1783)

试了一下，Deepseek这两个模型这样设置就可以用了：
- deepseek-ai/DeepSeek-V2.5
- deepseek-ai/DeepSeek-Coder-V2-Instruct

Qwen/Qwen2.5-Coder-7B-Instruct这个模型会返回一些啰里八嗦的东西，我试了下这个接口当前不支持stop这个参数，暂时将max_tokens设置小一点避免这个问题
![image](https://github.com/user-attachments/assets/928f2911-5cee-4cbf-8ea9-e2f94b60c109)

**Comment by lucacicii** [comment]
好的，谢谢
