### ISSUE TITLE
Automatic Removal of Duplicate Code Suggestions

### ISSUE THREAD

**Issue by taiwbi** [yzhengfei/ai-coding#209]
Currently, AI-generated code suggestions occasionally include parts of code that are already present, resulting in duplicate code that requires manual cleanup. Although this duplication is introduced by the AI model, it could be effectively managed by the plugin. Adding a feature to the plugin that automatically detects and removes duplicate (or very similar) code fragments before inserting them into the editor would greatly enhance usability.

#### Example

**Initial Code:**

```php
} catch (\Exception $e) {
    $this->notificationMessage
}
```

The cursor is at the end of the `$this->notificationMessage` line, and the AI-generated suggestion is:

```php
$this->notificationMessage = 'An error occurred while queueing messages. Please try again later.';
$this->notificationType = 'error';
$this->dispatch('notification');
```

If the user accepts this suggestion, the resulting code becomes:

```php
} catch (\Exception $e) {
    $this->notificationMessage$this->notificationMessage = 'An error occurred while queueing messages. Please try again later.';
    $this->notificationType = 'error';
    $this->dispatch('notification');
}
```

In this case, the `$this->notificationMessage` is duplicated, requiring manual deletion of one instance to ensure correct functionality.

It would greatly enhance the user experience if the plugin could detect these duplicated or similar fragments and remove them before suggesting or inserting code. This feature would prevent redundant code from being introduced and streamline the editing process.

**Comment by yzhengfei** [comment]
Thank you for your feedback. We have made optimizations in version 2024.1.19. If you still encounter this issue after downloading and installing, please provide the AI provider and model name. Thank you.
