### ISSUE TITLE
yi-34B-chat模型使用代码补全功能时token溢出

### ISSUE THREAD

**Issue by StarrySkyWill** [yzhengfei/ai-coding#249]
**问题**：激活code completion之后，选择Qianfan的yi-34b-chat (free)进行代码补全时报错。
**错误类型**：{"error_code":336007,"error_msg":"the max input characters is 8000","id":"..."}
**可能的错误原因**：根据Qianfan的文档，错误336007 
"the max input characters is xxx " 表示“请求长度不能超过最大字符限制，即用户输入大模型内容过长”。_在测试时，实际仅输入了“a =”两个字符。_
**可能的解决方法**：

1. 适当缩短输入；
2. 也可以通过千帆SDK调用避免此问题，当输入内容过长时，SDK会自动截断输入。（来自官方文档）

**错误截图：**
![image](https://github.com/user-attachments/assets/49b21d9f-26ac-4616-b9b6-cab877d8527f)

**Comment by yzhengfei** [comment]
![image](https://github.com/user-attachments/assets/f44fd768-a290-4657-bebf-afb17ed943e8)
你这里是不是设置过大了，将这里设置小一点试试，Qianfan的yi-34b-chat 我设置的4800刚刚测试是没问题的，具体代码提示的设置可以参考一下这个文档
https://plugins.jetbrains.com/plugin/21263-ai-coding/bang-zhu-wen-dang/dai-ma-zi-dong-bu-quan

**Comment by StarrySkyWill** [comment]
> ![image](https://private-user-images.githubusercontent.com/5087012/392676636-f44fd768-a290-4657-bebf-afb17ed943e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzODEzNDQsIm5iZiI6MTczMzM4MTA0NCwicGF0aCI6Ii81MDg3MDEyLzM5MjY3NjYzNi1mNDRmZDc2OC1hMjkwLTQ2NTctYmViZi1hZmIxN2VkOTQzZTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDVUMDY0NDA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDY3NTJiN2Y2NjI5NDY0M2E2NjJhZjMwZGQzNzNhZWEwMzliNjA0NTRjNjg1MzVjZjg4YjRhNjQ1YmYyYmE1MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.lI08TQdOUniwycOLmYQmu9wqSlT_1C9uhPethbuoRzM) 你这里是不是设置过大了，将这里设置小一点试试，Qianfan的yi-34b-chat 我设置的4800刚刚测试是没问题的，具体代码提示的设置可以参考一下这个文档 https://plugins.jetbrains.com/plugin/21263-ai-coding/bang-zhu-wen-dang/dai-ma-zi-dong-bu-quan

保持了默认的2800，刚刚试了一下4800，还是相同的报错。

**Comment by yzhengfei** [comment]
这是个bug，复现出了这个问题，下个版本会修复，非java语言传给AI的上下文来自编辑器打开的Tab页内容，打开的Tab页太多或者打开Tab页有大文件，就会导致此问题。

暂时先可以关闭过多的Tab页，或者在提示词模版中去除上下文内容（删除红框里的内容）解决这个问题

![image](https://github.com/user-attachments/assets/82498a5d-bd8f-42d5-868b-7fa46dea9df2)

**Comment by StarrySkyWill** [comment]
> 这是个bug，复现出了这个问题，下个版本会修复，非java语言传给AI的上下文来自编辑器打开的Tab页内容，打开的Tab页太多或者打开Tab页有大文件，就会导致此问题。
> 
> 暂时先可以关闭过多的Tab页，或者在提示词模版中去除上下文内容（删除红框里的内容）解决这个问题
> 
> ![image](https://private-user-images.githubusercontent.com/5087012/392729956-82498a5d-bd8f-42d5-868b-7fa46dea9df2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzODkzMDEsIm5iZiI6MTczMzM4OTAwMSwicGF0aCI6Ii81MDg3MDEyLzM5MjcyOTk1Ni04MjQ5OGE1ZC1iZDhmLTQyZDUtODY4Yi03ZmE0NmRlYTlkZjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDVUMDg1NjQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Nzk3ZWQ0MGYzNjFhZWMyMjE5NzU3ZTU4M2I4NzNiMTg4NTJiODdhYmY0ODkxMTg1MTBjY2Y1ZDNkODNjNTBlYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.eMsEV0NCDNkUy_G5XXNmolDiv1AeReTUoMhNxAF9n_U)

OK，非常感谢，稍候试一下您的解决方案，期待下个版本，加油！
