### ISSUE TITLE
Hope to add a manual trigger for auto completion. （希望能添加一个手动触发补全的功能）

### ISSUE THREAD

**Issue by lucacicii** [yzhengfei/ai-coding#57]
现状：很多时候在做了删除字符的操作后，需要按一下空格才会触发自动补全，但是自动补全完还需要手动删除空格。
期望：能自定义一个快捷键（或者先定义死一个也好）可以手动触发一次自动补全。类似于通义的alt + L
谢谢

**Comment by yzhengfei** [comment]
快捷键设置里可以自定义设置，具体设置路径如下：
<kbd>Settings/Preferences</kbd> > <kbd>Keymap</kbd> > <kbd>Main Menu</kbd> > <kbd>Code</kbd> > <kbd>Code Completion</kbd> > <kbd>Call Inline Completion</kbd>

![image](https://github.com/user-attachments/assets/40c4955c-c6bb-4bde-b50d-fb6506aac3cb)

**Comment by lucacicii** [comment]
谢谢
