### ISSUE TITLE
Cody integration not working 

### ISSUE THREAD

**Issue by nirzaf** [yzhengfei/ai-coding#70]
![image](https://github.com/user-attachments/assets/306a914f-381b-4519-a766-c24f8e49da55)

![image](https://github.com/user-attachments/assets/8fb2f46b-d570-4498-b6be-8ddd07a88585)

**Comment by yzhengfei** [comment]
![image](https://github.com/user-attachments/assets/cb87d38e-2101-4d6f-95fe-5b5b43b6c2d8)
Click the refresh button here
