### ISSUE TITLE
Add Option to Dock Chat Window to Sidebar in Rider

### ISSUE THREAD

**Issue by nirzaf** [yzhengfei/ai-coding#80]
Description: Currently, the chat window in Rider is not dockable to the sidebar, which can be inconvenient for users who prefer a more streamlined interface. This feature request is to add an option to move the chat window to the sidebar, similar to other chatting interfaces like GitHub Copilot chat and Cody.

Additional Information:

This feature would enhance the user experience by providing a cleaner and more organized workspace.
Similar functionality is available in other tools like Copilot and Cody, which allows users to dock their chat windows to the sidebar.

**Comment by yzhengfei** [comment]
Thank you for your feedback. The sidebar has been added in the latest version(AI Coding 2024.1.14). Download and install the latest version.
![image](https://github.com/user-attachments/assets/28c89ebf-982b-4dc5-b935-90b6bedd46d5)
